spring.application.name=TrucYNhan_QuanLyQuanCafe
#
# ===== Nếu lỗi "Port 8080 was already in use" thì bật lên =====


spring.datasource.url=jdbc:mysql://localhost:3306/trucynhan_coffee
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true